Fix error importing `createProxyMiddleware` function
When the `createProxyMiddleware` function is imported with curly braces ({}) like this:
` const { createProxyMiddleware } = require('http-proxy-middleware');`

it causes following error:
`createProxyMiddleware is not a function`

The `createProxyMiddleware` function works when imported without curly braces ({}):
`const createProxyMiddleware = require('http-proxy-middleware');`